log:
  logger-name: "daily_logger"
  filename: "logs/daily.txt"
  hour: 2
  minute: 30
db:
  sqlite:
    local: "./localDB.db"
server:
  concurrency: 0
  port: 8155
  authorization-code: 114514
  resource-path: "./public/"