log:
  logger-name: daily_logger
  filename: logs/daily.txt
  hour: 2
  minute: 30
db:
  path:
    local: ./localDB.db
server:
  redis:
    ip: "127.0.0.2"
    port: 6379
    password: "123456"
  concurrency: 0
  port: 8299
  token:
     secret: 321
     issuer: 123
  resource-path: ./public/